name       : ruby-netrc
version    : 0.11.0
release    : 2
source     :
    - https://rubygems.org/downloads/netrc-0.11.0.gem : de1ce33da8c99ab1d97871726cba75151113f117146becbe45aa85cb3dabee3f
license    : MIT
component  : programming.ruby
summary    : RubyGem - netrc
description: |
    This library can read and update netrc files, preserving formatting including comments and whitespace.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
